# Generated by Django 4.1 on 2022-09-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistitem',
            name='release_date',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='watched',
            field=models.CharField(max_length=500),
        ),
    ]
