# Generated by Django 4.1 on 2022-11-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0003_alter_watchlistitem_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistitem',
            name='release_date',
            field=models.CharField(max_length=500),
        ),
    ]
