# Generated by Django 4.1 on 2022-11-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0004_alter_watchlistitem_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistitem',
            name='release_date',
            field=models.DateField(),
        ),
    ]
